version: '3.8'

services:
  streak-core:
    image: alexpm11/streak_core:latest
    container_name: streak-core
    ports:
      - "8089:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
